# Generated by Django 3.2 on 2022-08-30 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('holiday', models.CharField(max_length=50, null=True)),
                ('open_hour', models.CharField(max_length=50, null=True)),
                ('menu', models.TextField()),
                ('lat', models.FloatField(null=True)),
                ('lng', models.FloatField(null=True)),
                ('signature', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='lesuire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('holiday', models.CharField(max_length=50, null=True)),
                ('menu', models.TextField()),
                ('lat', models.FloatField(null=True)),
                ('lng', models.FloatField(null=True)),
                ('link', models.TextField()),
                ('detail', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('holiday', models.CharField(max_length=50, null=True)),
                ('menu', models.TextField()),
                ('lat', models.FloatField(null=True)),
                ('lng', models.FloatField(null=True)),
                ('link', models.TextField()),
                ('signature', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lat', models.FloatField(null=True)),
                ('lng', models.FloatField(null=True)),
                ('tag', models.TextField()),
            ],
        ),
    ]
