# Generated by Django 3.2 on 2022-08-30 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='lesuire',
            new_name='Leisure',
        ),
    ]
